version: '3.5'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
            target: backend
        container_name: backend
        command: npm run serve
        volumes:
          - ./backend:/home/sensor/backend
        ports:
            - 8080:8080
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            target: frontend
        container_name: frontend
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - backend
        command: npm run start
        volumes:
          - ./frontend:/home/sensor/frontend
        ports:
            - 3000:3000