# GAE standard config
# https://cloud.google.com/appengine/docs/standard/nodejs/config/appref

runtime: nodejs14
service: default

instance_class: F1

automatic_scaling:
    min_instances: 0
    max_instances: 1